export default {
  CHANGE_FROM_SCHEME: 'CHANGE_FROM_SCHEME',
  CHANGE_TO_SCHEME: 'CHANGE_TO_SCHEME',
  CHANGE_INPUT_TEXT: 'CHANGE_INPUT_TEXT',
  CHANGE_OUTPUT_TEXT: 'CHANGE_OUTPUT_TEXT',
  CONVERT: 'CONVERT',
};
